[project]
name = "konovo"
version = "1.0.0"
description = "Konovo full-stack task"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.0",
    "httpx>=0.28.1",
]

[dependency-groups]
dev = [
    "ruff>=0.12.2",
    "ty>=0.0.1a14",
]
